### ISSUE TITLE
7/27/2017 - Current application state: UI review

### ISSUE THREAD

**Issue by aaneitchik** [exadel-team/staffapp-web#54]
**Пользователь**: example@gmail.com
**Ветка**: develop

Наши с Антоном замечания по UI:

## Логин:
1. Исправить ошибки и предупреждения в консоли.
2. Клик на лого - переход на главную страницу.
3. Клик на имя юзера в хэдере - показать дропдаун с возможность выйти (logout).
4. Если юзер залогинен, localhost:3000 должен перенаправлять на главную страницу, а не на логин.
5. Большая пауза после ввода имейла, непонятно, что происходит (покажите лоудер где-нибудь)

## Список интервью:
1. Лоудинг-заглушка(эти серенькие полосы) должны быть примерно похожи на текст, который в них будет написан (посмотрите, например, на Bitbucket в левое меню).
Если не получается - лучше просто лоудер покажите.
2. Ну думаю понятно, что карточки с интервью надо перестилить. Давайте найдем красивый сайтик какой-нибудь, и будем с него слизывать стили.
3. На ховер у карточки с интервью (да и у любой карточки) должны как-то меняться стили (меняться цвет, например, а еще лучше добавьте box-shadow). Просто погуглите css card style

## Интервью:
1. Если сначала открыть Иванова, потом вернуться наад к списку интервью, и открыть Сидорова - сначала вместо лоудера будет показываться инфа про Иванова, и только потом появится про Сидорова.
2. Если нет Secondary skills, то нужно этот кейс красиво обработать, а не писать "Secondary skills: " и ничего больше

## Фидбек форма:
Если все приложение выглядит плохо, то фидбэк форма ни в какие ворота.
1. Застилить.
2. Добавить что-нибудь в духе звездочек для оценки скилла, вместо этого селекта.
3. Вместо input.textarea - реальную textarea!!
4. Если в форме нет Minor Skills и Other Skills - не показывать их вообще.
5. На сабмитать эту форму на Enter - она слишком большая и очень легко засабмитать случайно.
6. Нет никакой валидации - исправить.
7. Нужен модальник для подтверждения, для начала - хотя бы просто "Are you sure?"
8. На странице фибека не хватает инфы, на кого оставляю фидбэк.

**Comment by Dosant** [comment]
@Logopeddd, @sergey-moiseyenko, @NickZabolotskiy  Есть прогресс по этому?

**Comment by Logopeddd** [comment]
определённо, уже почти всё исправили
